# Generated by Django 5.0.6 on 2024-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('n_allowed_requests', models.IntegerField(default=100)),
                ('n_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
