# Generated by Django 5.0.6 on 2024-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_apikey_end_date_apikey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
