# Generated by Django 5.0.6 on 2024-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_apikey_end_date_alter_apikey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='n_allowed_requests',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
