# Generated by Django 5.0.6 on 2024-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_apikey_n_allowed_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='n_allowed_requests',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
